#!/opt/hermes/.venv/bin/python
"""hermes-init helper: seed /opt/data/config.yaml from the kit's config.yaml, deep-merging
config.copilot.yaml on top when COPILOT_MODEL is set. Never overwrites an existing config."""
import os
import sys

import yaml

seed_dir, target = sys.argv[1], sys.argv[2]
if os.path.exists(target):
    print(f"[init] {target} already present, left untouched (delete it to re-seed)")
    sys.exit(0)


def merge(base, over):
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            merge(base[k], v)
        else:
            base[k] = v
    return base


with open(os.path.join(seed_dir, "config.yaml"), encoding="utf-8") as fh:
    cfg = yaml.safe_load(fh) or {}
layers = ["config.yaml"]
if os.environ.get("COPILOT_MODEL", "").strip():
    with open(os.path.join(seed_dir, "config.copilot.yaml"), encoding="utf-8") as fh:
        merge(cfg, yaml.safe_load(fh) or {})
    layers.append("config.copilot.yaml")
with open(target, "w", encoding="utf-8") as fh:
    fh.write("# Generated by hermes-init from " + " + ".join(layers) + ". Edit here or delete to re-seed.\n")
    yaml.safe_dump(cfg, fh, sort_keys=False, allow_unicode=True)
print(f"[init] seeded {target} from {' + '.join(layers)}")
