#!/opt/hermes/.venv/bin/python
"""hermes-init helper: seed /opt/data/config.yaml from the kit's config.yaml, deep-merging
config.copilot.yaml on top when COPILOT_MODEL is set. Never overwrites an existing config."""
import os
import sys

import yaml

import shutil
import stat
import subprocess

seed_dir, target = sys.argv[1], sys.argv[2]
data_dir = os.path.dirname(target)


def seed_assistant_profile() -> None:
    """Create the `assistant` profile (own SOUL, config, memory, cron) and its workspace."""
    name = "assistant"
    profile_dir = os.path.join(data_dir, "profiles", name)
    if not os.path.exists(os.path.join(profile_dir, "config.yaml")):
        if not os.path.isdir(profile_dir):
            cmd = ["/opt/hermes/.venv/bin/hermes", "profile", "create", name, "--no-alias",
                   "--description", "Personal work assistant: tasks, deadlines, meetings, reminders, briefings"]
            r = subprocess.run(cmd, env={**os.environ, "HERMES_HOME": data_dir}, capture_output=True, text=True)
            print(f"[init] hermes profile create {name}: rc={r.returncode} {r.stdout.strip()[-300:]} {r.stderr.strip()[-300:]}")
            os.makedirs(profile_dir, exist_ok=True)
        shutil.copy(os.path.join(seed_dir, "assistant", "config.yaml"), os.path.join(profile_dir, "config.yaml"))
        shutil.copy(os.path.join(seed_dir, "assistant", "SOUL.md"), os.path.join(profile_dir, "SOUL.md"))
        print(f"[init] seeded {profile_dir}/config.yaml and SOUL.md")
    else:
        print(f"[init] {profile_dir}/config.yaml already present, left untouched")
    # per-profile .env: the multiplexed gateway brings up each profile's channels from ITS .env
    env_path = os.path.join(profile_dir, ".env")
    wanted = {k: os.environ.get(k, "") for k in ("NTFY_TOPIC", "NTFY_PUBLISH_TOPIC", "NTFY_SERVER_URL",
                                                  "NTFY_TOKEN", "NTFY_HOME_CHANNEL", "NTFY_MARKDOWN")}
    wanted = {k: v for k, v in wanted.items() if v}
    if wanted:
        existing = open(env_path, encoding="utf-8").read() if os.path.exists(env_path) else ""
        lines = [ln for ln in existing.splitlines() if not ln.split("=", 1)[0].strip() in wanted]
        lines += [f"{k}={v}" for k, v in wanted.items()]
        with open(env_path, "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines) + "\n")
        os.chmod(env_path, 0o600)
        print(f"[init] wrote {len(wanted)} NTFY_* keys into {env_path}")
    # workspace with the task/agenda files
    ws = os.path.join(data_dir, "assistant")
    if not os.path.exists(os.path.join(ws, "tasks.md")):
        shutil.copytree(os.path.join(seed_dir, "assistant", "workspace"), ws, dirs_exist_ok=True)
        print(f"[init] seeded assistant workspace at {ws}")
    # same guard plugin, root-owned and read-only inside the profile
    plug_src = os.path.join(seed_dir, "plugins", "git-guard")
    plug_dst = os.path.join(profile_dir, "plugins", "git-guard")
    if os.path.isdir(plug_src):
        if os.path.isdir(plug_dst):
            shutil.rmtree(plug_dst)
        shutil.copytree(plug_src, plug_dst, ignore=shutil.ignore_patterns("__pycache__"))
        for root, dirs, files in os.walk(plug_dst):
            os.chmod(root, 0o755)
            for f in files:
                os.chmod(os.path.join(root, f), 0o644)
        print(f"[init] installed read-only git-guard copy at {plug_dst} (root-owned)")


if os.path.exists(target):
    print(f"[init] {target} already present, left untouched (delete it to re-seed)")
    if os.environ.get("ASSISTANT_PROFILE", "").strip():
        seed_assistant_profile()
    sys.exit(0)


def merge(base, over):
    for k, v in over.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            merge(base[k], v)
        else:
            base[k] = v
    return base


with open(os.path.join(seed_dir, "config.yaml"), encoding="utf-8") as fh:
    cfg = yaml.safe_load(fh) or {}
layers = ["config.yaml"]
# (env var that enables it, overlay file). An overlay is merged only when its var is non-empty.
OVERLAYS = [
    ("COPILOT_MODEL", "config.copilot.yaml"),
    ("FLOWGEAR_MCP_URL", "config.flowgear.yaml"),
    ("ATLASSIAN_MCP_AUTH", "config.atlassian.yaml"),
]
for var, fname in OVERLAYS:
    path = os.path.join(seed_dir, fname)
    if os.environ.get(var, "").strip() and os.path.exists(path):
        with open(path, encoding="utf-8") as fh:
            merge(cfg, yaml.safe_load(fh) or {})
        layers.append(fname)
with open(target, "w", encoding="utf-8") as fh:
    fh.write("# Generated by hermes-init from " + " + ".join(layers) + ". Edit here or delete to re-seed.\n")
    yaml.safe_dump(cfg, fh, sort_keys=False, allow_unicode=True)
print(f"[init] seeded {target} from {' + '.join(layers)}")
if os.environ.get("ASSISTANT_PROFILE", "").strip():
    seed_assistant_profile()
